### ISSUE TITLE
[UI]: Network views need some padding 

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/explorer#133]
### Issue description

The network views in the network selector need some padding.

<img width="1358" alt="Bildschirmfoto 2022-02-09 um 21 52 56" src="https://user-images.githubusercontent.com/17240275/153288083-6f8ab7db-1e1d-4450-bc8a-0da238958ac9.png">

### Expected behaviour

space

### Actual behaviour

no space

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker for this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MaKla89** [comment]
Left-Side padding / margin of the "Network Selection" also affected on mobile version. See screenshot:
![Screenshot_20220209-223614_Brave](https://user-images.githubusercontent.com/33317175/153295311-f8b4e730-4d19-4629-9e2f-5eaf835bdb3e.jpg)

**Comment by laumair** [comment]
Fixed in https://github.com/iotaledger/explorer/pull/160

**Comment by r-c-k** [comment]
Hey @laumair, seems like it is not fixed yet.
`Safari 15.5`

<img width="851" alt="Bildschirmfoto 2022-05-18 um 14 55 06" src="https://user-images.githubusercontent.com/17240275/169043524-2d84ca06-e9dc-4ffe-912f-7b9c2c289372.png">
